config/routes.rb
Rails.application.routes.draw do
  resources :resources
  root 'static#index'
  get  'static/gitworkflow'
  get  'static/octocat'
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: 'Resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:name, :url)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
  def gitworkflow
  end
  def octocat
  end
end

app/views/layouts/_nav.html.erb
<ul id="nav">
  <li id="navli"><%= image_tag "github-icon2.png" %></li>
  <%= link_to "Home", root_path %>&nbsp; | &nbsp;
  <%= link_to "Git Workflow", static_gitworkflow_path %>&nbsp; | &nbsp;
  <%= link_to "Resources", resources_path %>&nbsp; | &nbsp;
  <%= link_to "Octocats", static_octocat_path %>&nbsp; |&nbsp;
  <li id="navli"><a href="https://github.com/jendiamond">GitHub</a></li>&nbsp;|&nbsp;
  <li id="navli"><a href="https://gist.github.com/jendiamond">Gists</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntroToGitJendiamondRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<%= render 'layouts/nav' %>
<div id="resources">
  <h2>RESOURCES</h2>
  <h2>Git with Jen Diamond</h2>
  <ul>
    <li>Introduction to Git and GitHub</li>
    <li>thejendiamond@gmail.com</li>
    <li><a href="https://github.com/jendiamond">Jen Diamond's GitHub</a></li>
    <li><a href="https://gist.github.com/jendiamond/18d9c1e9e801d894777a5632394034c1#git-with-jen-diamond">Intro to Git and GitHub Gist</a></li>
    <li><a href="https://github.com/gitwithjendiamond">gitwithjendiamond GitHub Organization</a></li>
    <li><a href="http://madpad.herokuapp.com/git">MadPad/git</a></li>
    <li><a href="https://b.socrative.com/login/student/">Git Quiz / Room AIZHWCIH</a></li>
    <li><a href="https://git-scm.com/documentation">Git Docs</a></li>
    <li><a href="http://daringfireball.net/projects/markdown/basics">Markdown</a></li>
    <li><a href="https://try.github.io/levels/1/challenges/1">Try Git</a></li>
    <li><a href="https://www.atlassian.com/git/">Git by Atlassian</a></li>
    <li><a href="https://bitbucket.org">Bitbucket</a></li>
    <li><a href="http://think-like-a-git.net/">Think Like (a) Git</a></li>
    <li><a href="http://marklodato.github.io/visual-git-guide/index-en.html">A Visual Git Reference</a></li>
    <li><a href="http://rogerdudler.github.io/git-guide/">The simple guide</a></li>
    <li><a href="https://help.github.com/">GitHub Help</a></li>
    <li><a href="http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html">A Note About Git Commit Messages</a></li>
    <li><a href="https://robots.thoughtbot.com/no-newline-at-end-of-file">Always add a newline at the end of your file</a></li>
    <li><a href="http://www.urbandictionary.com/define.php?term=Git">Definition ;)</a></li>
  </ul>
</div>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.url %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @resource.url %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>